# Generated by Django 5.2.17 on 2026-09-11 11:43

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.SlugField(max_length=100, unique=True)),
                (
                    "level",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("revision", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="ImportBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset_key", models.SlugField(max_length=100)),
                ("level", models.PositiveSmallIntegerField()),
                ("filename", models.CharField(max_length=255)),
                ("digest", models.CharField(max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("errors", models.JSONField(default=list)),
                ("base_revision", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("applied_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="Learner", max_length=80)),
                (
                    "theme",
                    models.CharField(
                        choices=[("system", "System"), ("light", "Light"), ("dark", "Dark")],
                        default="system",
                        max_length=10,
                    ),
                ),
                (
                    "font_size",
                    models.PositiveSmallIntegerField(
                        default=40,
                        validators=[
                            django.core.validators.MinValueValidator(24),
                            django.core.validators.MaxValueValidator(64),
                        ],
                    ),
                ),
                ("examples", models.BooleanField(default=True)),
                (
                    "daily_new",
                    models.PositiveSmallIntegerField(
                        default=10, validators=[django.core.validators.MaxValueValidator(100)]
                    ),
                ),
                (
                    "session_size",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("ja_en", "Japanese → English"),
                            ("en_ja", "English → Japanese"),
                            ("both", "Both directions"),
                        ],
                        default="ja_en",
                        max_length=10,
                    ),
                ),
                (
                    "ordering",
                    models.CharField(
                        choices=[("source", "Source order"), ("shuffle", "Shuffle new cards")],
                        default="source",
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=100)),
                ("position", models.PositiveIntegerField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.dataset"
                    ),
                ),
            ],
            options={
                "ordering": ["dataset__level", "position"],
            },
        ),
        migrations.CreateModel(
            name="Entry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("serial", models.PositiveIntegerField()),
                ("position", models.PositiveIntegerField()),
                ("batch", models.PositiveIntegerField(default=1)),
                ("kana", models.TextField()),
                ("english", models.TextField()),
                ("example", models.TextField(blank=True)),
                ("example_eng", models.TextField(blank=True)),
                ("search", models.TextField()),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.dataset"
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.lesson"
                    ),
                ),
            ],
            options={
                "ordering": ["-dataset__level", "lesson__position", "position"],
            },
        ),
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("filters", models.JSONField(default=dict)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "entries",
                    models.ManyToManyField(
                        blank=True, related_name="collections", to="learning.entry"
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CardState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("ja_en", "Japanese → English"), ("en_ja", "English → Japanese")],
                        max_length=5,
                    ),
                ),
                ("state", models.JSONField(default=dict)),
                ("due", models.DateTimeField(null=True)),
                ("introduced_at", models.DateTimeField(null=True)),
                ("suspended", models.BooleanField(default=False)),
                ("revision", models.PositiveIntegerField(default=0)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="learning.entry",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("tags", models.CharField(blank=True, max_length=500)),
                ("bookmarked", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotations",
                        to="learning.entry",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("mode", models.CharField(default="cards", max_length=10)),
                ("filters", models.JSONField(default=dict)),
                ("queue", models.JSONField(default=list)),
                ("cursor", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.profile"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("rating", models.PositiveSmallIntegerField()),
                ("reviewed_at", models.DateTimeField()),
                ("before", models.JSONField()),
                ("after", models.JSONField()),
                ("scheduler", models.JSONField()),
                ("scheduler_version", models.CharField(max_length=40)),
                ("session_cursor", models.PositiveIntegerField()),
                ("undone", models.BooleanField(default=False)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.cardstate"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.studysession"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PracticeAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("answer", models.TextField()),
                ("correct", models.BooleanField()),
                ("self_assessment", models.BooleanField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="learning.entry"
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="learning.studysession"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("dataset", "label"), name="unique_source_lesson"
            ),
        ),
        migrations.AddIndex(
            model_name="entry",
            index=models.Index(
                fields=["lesson", "batch", "position"], name="learning_en_lesson__086278_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entry",
            constraint=models.UniqueConstraint(
                fields=("dataset", "serial"), name="unique_source_serial"
            ),
        ),
        migrations.AddConstraint(
            model_name="preset",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="unique_preset_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="collection",
            constraint=models.UniqueConstraint(
                fields=("profile", "name"), name="unique_collection_name"
            ),
        ),
        migrations.AddIndex(
            model_name="cardstate",
            index=models.Index(
                fields=["profile", "suspended", "due"], name="learning_ca_profile_cb4b30_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cardstate",
            constraint=models.UniqueConstraint(
                fields=("profile", "entry", "direction"), name="unique_learner_card"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotation",
            constraint=models.UniqueConstraint(
                fields=("profile", "entry"), name="unique_annotation"
            ),
        ),
    ]
